---
- name: Stop Tomcat
  ssh: service tomcat stop

- name: Delete app ROOT, ROOT.war
  shell: rm -rf {{deploy_path}}/webapps/{{application}}.war
  sudo: True

- name: copy app war to tomcat/webapps
  copy: src={{ item }} dest={{deploy_path}}/tomcat-{{app}}/webapps/ROOT.war owner={{tomcat_user}}
  with_fileglob:
    - "{{deploy_war_path}}/*.war"

- name: Change ownership of Tomcat webapps/ROOT.war
  file: path={{deploy_path}}/tomcat-{{app}}/webapps/ROOT.war owner={{tomcat_user}} group={{tomcat_group}}


- name: supervisor start tomcat service
  shell: service tomcat start

- name: wait for tomcat to start
  wait_for: port={{appport}} timeout=15
